[package]
name = "dot15d4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dot15d4-macros = { path = "../dot15d4-macros" }

tracing = { version = "0.1.38", default-features = false }
bitflags = "2.4.2"
heapless = "0.8.0"
critical-section = "1.1"
pollster = "0.3"

colored = { version = "2", optional = true }
clap = { version = "4.5.1", features = ["derive"], optional = true }
hex = { version = "0.4.3", optional = true }

[dev-dependencies]
tracing-subscriber = "0.3"
critical-section = { version = "1.1", features = ["std"] }

[features]
std = []
default = ["std"]
dot15d4-cat = ["std", "colored", "clap", "hex"]

[[bin]]
name = "dot15d4-cat"
required-features = ["dot15d4-cat"]
