[package]
name = "dot15d4-fuzz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "0.15.3"
dot15d4 = { path = "../dot15d4" }
