name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Miri
      run: |
        rustup toolchain install nightly --component miri
        cargo +nightly miri setup
    - name: Install AFL
      run: cargo install cargo-afl
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Miri on sync
      run: cargo +nightly miri test -p dot15d4 sync

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lints
      run: cargo clippy --all-features --all-targets
    - name: Fmt
      run: cargo fmt --check --verbose

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v1
